### ISSUE TITLE
Stabilization plan for release 1.1

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2855]
Before the branch split:

* [x] Review the C# 7.1-7.3 APIs to see if there are any syntax nodes for language features we haven't considered yet (#2870) 
* [x] Review blocking issues for the [1.1 release](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/milestone/33)
* [x] Complete items targeted to [1.1-beta.next](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/milestone/48)
* [x] Remove **StyleCopAnalyzers.dev.snk** and various hooks related to it (#2856)
* [x] Remove scripts that are not required with the new deployment strategy (#2856)

Branch split:

* [x] Merge **master** to **stabilization**
* [x] Update **stabilization** to 1.1.1-rc
* [x] Update **master** to 1.2.0-beta

After one month without a blocking bug filed against the **stabilization** branch:

* [x] Update **stabilization** to 1.1.1 (#2944)

**Comment by Kantuz001** [comment]
any news?

**Comment by Birgos** [comment]
Is there already a plan or an official date for the release of the stable version 1.1.0?

**Comment by EskeN** [comment]
any update?

**Comment by TannerBragg** [comment]
This project is highly anticipated.  Any updates?

**Comment by sharwell** [comment]
I should be able to get 1.1.1 published in the first half of next week. It was due earlier in the month but I didn't get a chance to make the update yet.

**Comment by TannerBragg** [comment]
@sharwell could you please review #2942 prior to the 1.1 release.  It could be a very nice feature...

**Comment by sharwell** [comment]
@TannerBragg The 1.1 release is only considering critical blocking bugs at this point.

**Comment by sharwell** [comment]
This is now shipped as stable release version 1.1.118.
